notifications:
  email:
    - georgi.kojuharov@siteground.com
language: php
node_js:
  - "12.13"
before_install:
  - npm install -g npm@12.13
install:
  - php prepare.php
script:
  - php test.php
after_script:
  - php report.php
  - php cleanup.php
