sudo: false

language: php

branches:
  only:
    - master

install:
  - php prepare.php

script:
  - phpenv config-rm xdebug.ini
  - travis_wait 30 php test.php

after_script:
- php report.php
- php cleanup.php
