sudo: false

language: php
php:
  - '7.0'

branches:
  only:
    - master
before_install:
  - echo 'suhosin.executor.include.whitelist = phar' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - phpenv config-rm xdebug.ini
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php
