sudo: false

language: php

branches:
  only:
    - master
before_install:
  - echo 'suhosin.executor.include.whitelist = phar' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - php prepare.php
