notifications:
  email:
    - georgi.kojuharov@siteground.com
language: php
node_js:
  - node

before_install:
  - npm install -g npm@latest
  - nvm install node

install:
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php
