sudo: false

language: php

branches:
  only:
    - master

install:
  - php prepare.php
  
before_script:
  - echo 'suhosin.executor.include.whitelist = phar' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - php test.php

after_script:
- php report.php
- php cleanup.php
