sudo: false

notifications:
  email:
    - georgi.kojuharov@siteground.com
    
language: php
php:
  - '7.4'

branches:
  only:
    - master
    
install:
  - phpenv config-rm xdebug.ini
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php
