sudo: false

notifications:
  email:
    - georgi.kojuharov@siteground.com
    
language: php
php:
  - '7.3'
node_js:
  - node

branches:
  only:
    - master
    
before_install:
  - npm install -g npm@latest
    
install:
  - phpenv config-rm xdebug.ini
  - php prepare.php

script:
  - php test.php

after_script:
  - php report.php
  - php cleanup.php
